name: DEPLOY CI
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repositoryName: realwds/hexo-blog
        BRANCH: gh-pages
        BUILD_SCRIPT: npm install hexo-cli -g && npm install && hexo clean && hexo d
        FOLDER: public
